# Source: grafana/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: grafana
  namespace: jx-observability
  labels:
    helm.sh/chart: grafana-6.17.4
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/version: "8.2.2"
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: 'grafana'
type: Opaque
data:
  admin-user: "YWRtaW4="
  admin-password: "ZmFrZXBhc3N3b3Jk"
  ldap-toml: ""
