filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx-staging
repositories:
- name: dev
  url: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts
releases:
- chart: dev/jx3-golang-http
  version: 0.0.2
  name: jx3-golang-http
  values:
  - jx-values.yaml
- chart: dev/jx3-lensdevopscare-demo
  version: 0.0.2
  name: jx3-lensdevopscare-demo
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
