# Source: cd-indicators/templates/secret_grafana_datasource.yaml
apiVersion: v1
kind: Secret
metadata:
  name: cd-indicators-grafana-datasource
  labels:
    app.kubernetes.io/name: cd-indicators
    app.kubernetes.io/instance: "cd-indicators"
    helm.sh/chart: cd-indicators-0.0.13
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: "Helm"
    jenkins-x.io/grafana-datasource: "1"
  annotations:
    meta.helm.sh/release-name: 'cd-indicators'
  namespace: jx
stringData:
  postgres.yaml: |-
    apiVersion: 1
    datasources:
      - name: Indicators
        uid: indicators
        type: postgres
        url: cd-indicators-postgresql.jx:5432
        database: indicators
        user: postgres
        secureJsonData:
          password: "password"
        jsonData:
          connMaxLifetime: 14400
          maxIdleConns: 2
          maxOpenConns: 10
          postgresVersion: 1200
          sslmode: disable
