# Source: cd-indicators/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: cd-indicators
  labels:
    app.kubernetes.io/name: cd-indicators
    app.kubernetes.io/instance: "cd-indicators"
    helm.sh/chart: cd-indicators-0.0.13
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: 'cd-indicators'
  namespace: jx
stringData:
  postgresql-host: cd-indicators-postgresql.jx
  postgresql-port: 5432
  postgresql-database: indicators
  postgresql-username: postgres
  postgresql-password: password
  grafana-datasource-postgresql-json-data: |
    {"connMaxLifetime":14400,"maxIdleConns":2,"maxOpenConns":10,"postgresVersion":1200,"sslmode":"disable"}
